name: Build and Push Image

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: sasaksacrtest.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sasaksacrtest.azurecr.io/sas-test-app:latest # ${{ secrets.IMAGE_TAG }}
          file: Dockerfile
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
#
#      - name: Log in to GitHub container registry
#        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
#        with:
#          registry: sasaksacrtest.azurecr.io
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Lowercase the repo name and username
#        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
#
#      - name: Build and push container image to registry
#        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
#        with:
#          push: true
#          tags: sasaksacrtest.azurecr.io/sas-test-app:latest
#          file: ./Dockerfile
